### ISSUE TITLE
Do not update/query if property already set

### ISSUE THREAD

**Issue by peter-wangxu** [emc-openstack/storops#101]
when user creates a new lun with `lun_id` or `name`, storops should not fetch all properties from remote, instead, only return the value set by user:

```python
In [4]: import storops

In [5]: vnx = storops.VNXSystem('192.168.1.50', 'sysadmin', 'sysadmin')

In [6]: lun = vnx.get_lun(lun_id=1)

In [7]: lun.lun_id
No handlers could be found for logger "storops.vnx.navi_command"
Out[7]: 1

In [8]:

```

You can see, a query was sent when `lun.lun_id`

Thanks
Peter

**Comment by yong-huang** [comment]
Won't support it, close this ticket.
