### ISSUE TITLE
Nova instance (Mitaka) can't attach volumes created in UnityOVA

### ISSUE THREAD

**Issue by lucker6666** [emc-openstack/storops#118]
1. install the openstack mitaka on redhat7 by using packstack.
2. install the emc unity driver for mitaka
3. use cinder to create the volume on unityova -- succsss
4. attach this volume to nova instance -- failure

the log attached

[volume.txt](https://github.com/emc-openstack/storops/files/877535/volume.txt)

**Comment by peter-wangxu** [comment]
root cause: storops treats redhat initiator(`iqn.1994-05.com.redhat:4dc0b7e1edc9`) as invalid format, and refuses to connect it with Unity.
