### ISSUE TITLE
To many `SystemAPINotSupported` messages logged

### ISSUE THREAD

**Issue by Murray-LIANG** [emc-openstack/storops#143]
In the test environment, I connected a driver to a Falcon array. Some APIs invoked by storops are not supported in Falcon array.
But in the log file, almost every rest request logged the same message:
```
None req-b3d3a404-9652-45b2-a61f-67d7df3fac7d admin None] <== _terminate_connection: return (5338ms) None: SystemAPINotSupported: System in version {version} doesn't support this API
```
There should not log the message there.

**Comment by jicahoo** [comment]
I will try to fix it.

**Comment by yong-huang** [comment]
Won't fix it, close this ticket.
