### ISSUE TITLE
Capacity Report Enhancement

### ISSUE THREAD

**Issue by Tianqi-Tang** [emc-openstack/storops#15]
This is a planned content:
1. Update README to include the capacity report feature
2. Refine the round_it utilities.

**Comment by sunnyrarora** [comment]
Hi Team,
I was thinking that- Is there any way to pull "Capacity Report" by storops ?

Thanks
Regards

Sunny

**Comment by Tianqi-Tang** [comment]
Hi Sunny,

The capacity information can be retrived from storops by 

from storops import VNXSystem
vnx = VNXSystem('ip', 'username', 'password')
capacity = VNXSystem.get_capacity()
print(capacity)

Thanks,
Tina

**Comment by jealous** [comment]
I am closing this issue because the fix has been merged.  Please feel free to open a new issue if this enhancement doesn't fit the requirement.
