### ISSUE TITLE
Tier capacity per pool

### ISSUE THREAD

**Issue by jbs727** [emc-openstack/storops#162]
Hello,
Is there a way to get the tiers and their capacity in each particular pool? In naviseccli I can get the below output:

```
# naviseccli storagepool -list -tiers -name SILVER
Pool Name:  SILVER
Pool ID:  1

Tier Name:  Extreme Performance
Raid Type:  r_5
User Capacity (GBs):  2930.21
Consumed Capacity (GBs):  2638.39
Available Capacity (GBs):  291.82
Percent Subscribed:  90.04%
Data Targeted for Higher Tier (GBs):  0.00
Data Targeted for Lower Tier (GBs):  226.44
Disks (Type):
...

Tier Name:  Performance
Raid Type:  r_5
User Capacity (GBs):  30050.08
Consumed Capacity (GBs):  27045.22
Available Capacity (GBs):  3004.86
Percent Subscribed:  90.00%
Data Targeted for Higher Tier (GBs):  222.93
Data Targeted for Lower Tier (GBs):  22.04
Disks (Type):
...
```

The ```VNXPool``` does not appear to have this information even though it is calling ```naviseccli storagepool -list -all -name SILVER```, of which ```-tiers``` is a subset in the CLI.

Regards,
Jeff

**Comment by peter-wangxu** [comment]
Hi @jbs727 `VNXPool` is not providing the mentioned properties for now.

You can create a PR for this if you are eager for this function.

Either, we will fix it in a later patch and let you.

**Comment by jbs727** [comment]
Thanks for the confirmation @peter-wangxu. I'm more than happy to wait for a later patch.

**Comment by peter-wangxu** [comment]
@jbs727 Please take a look of the PR, you can try the PR and give me feedbacks.

**Comment by peter-wangxu** [comment]
Hi @jbs727 the requested feature is now in https://github.com/emc-openstack/storops/releases/tag/r0.5.3

I am closing the issue.

Thanks
Peter
