### ISSUE TITLE
Unity - Add metrics for Raw Space in get_system_capacity

### ISSUE THREAD

**Issue by But4ler** [emc-openstack/storops#168]
Hello
In the Unity API, a metrics on the remaining raw space or unconfigured drive in the array would be interesting.
Example, in "get_system_capacity".
Acctually, we just know the number of disks not configured via the "get_disk_group"

**Comment by yong-huang** [comment]
We don't have plan to add this metrics into get_system_capacity, because it is not follow the Unity Object Model. If you need to get this metrics, suggest implementing in the application. Thanks for the feedback.
