### ISSUE TITLE
Support for VMware/VMFS style LUNs

### ISSUE THREAD

**Issue by lingfish** [emc-openstack/storops#191]
Hi, wondering if there's any plans to support these?  A co-worker, @ddisisto has done a bit of work here (which he'll share), but it would be good to know your plans too.

(Edit: to clarify, I don't mean VVols.)

**Comment by lingfish** [comment]
Hi, not sure I would agree with the label "feature"; Unity isn't fully supported, so it would be good to get that done.

**Comment by peter-wangxu** [comment]
The feature tag means the storops doesn't support it yet. The extra effort is needed to make it available in storops

**Comment by lingfish** [comment]
Hi, when will that effort be made? Thanks.

**Comment by lingfish** [comment]
When attempting to rename a VMFS LUN:

```

---------------------------------------------------------------------------
UnityResourceNotFoundError                Traceback (most recent call last)
<ipython-input-288-e0fa57f99a99> in <module>()
----> 1 lun.name = 'Misc2'

/home/user/.virtualenvs/ucs/lib/python2.7/site-packages/storops/unity/resource/lun.pyc in name(self, new_name)
     78     @name.setter
     79     def name(self, new_name):
---> 80         self.modify(name=new_name)
     81 
     82     @property

/home/user/.virtualenvs/ucs/lib/python2.7/site-packages/storops/unity/resource/lun.pyc in modify(self, name, size, host_access, description, sp, io_limit_policy, is_repl_dst, tiering_policy, snap_schedule, is_compression)
    180         resp = self._cli.action(UnityStorageResource().resource_class,
    181                                 self.get_id(), 'modifyLun', **req_body)
--> 182         resp.raise_if_err()
    183         return resp
    184 

/home/user/.virtualenvs/ucs/lib/python2.7/site-packages/storops/unity/resp.pyc in raise_if_err(self)
    129         if self.has_error():
    130             ex_clz = get_rest_exception(self.error_code)
--> 131             raise ex_clz(self.error)
    132 
    133     @property

UnityResourceNotFoundError: The requested resource does not exist. (Error Code:0x7d13005)

```

**Comment by lingfish** [comment]
Hi, I'm following up on this -- when will VMFS LUNs be fully supported?

It is incredibly frustrating that one cannot remove all VMFS LUNs from a host in Unisphere, and this library doesn't have any way to either, that I can work out.

**Comment by DingDino** [comment]
@lingfish 

We have tested this branch of VMFS LUN feature.
Now: 
1. You can use create_vmfs() in storops_test/unity/resource/test_pool.py to create VMFS LUN.
2. There is property called 'is_vmware_vmfs' to check whether the lun is VMFS. 
It's just to check the 'type'  of UnityLun, see if it is "LUNTypeEnum.VMWARE_ISCSI".
Then you can filter the VMFS lun from all luns.

A piece of code show the create, filter and delete operations:

	unity = UnitySystem('10.10.10.10', 'user_name', 'password')
    pool = unity.get_pool('pool_1')
    for i in range(5):
        vmfs = pool.create_vmfs(vmfs_name="VMFS datastore_" + str(i), size_gb=10)
    vmfs_list = unity.get_lun()
    for lun in vmfs_list:
        if lun.is_vmware_vmfs:
            lun.delete()

Thanks,
Ding Dong

**Comment by lingfish** [comment]
Thanks, will give this a shot on the weekend.

Any thoughts on how to iterate over all VMFS LUNs attached to a host, and remove access (_not_ remove the whole LUN)?

And what about avoiding all the individual rescans that OE does?  Or is that fixed in OE 5?

**Comment by DingDino** [comment]
@lingfish 

Hi, I did not get your question well, also no idea about what fixes in OE 5.

Here is the test I made on Unity with software version: 5.0.1.0.5.010

    unity = UnitySystem('10.10.10.10', 'user_name', 'password')
    # or you can give a host name to get a specific host
    hosts = unity.get_host()
    for host in hosts:
        # get luns on host
        luns_on_host = host.host_luns
        if luns_on_host:
            for host_lun in luns_on_host:
                lun_id = host_lun.lun.id
                lun = unity.get_lun(_id=lun_id)
                # filter the vmfs on this host
                if lun.is_vmware_vmfs:
                    # remove the host_access
                    lun.modify(host_access=[])

With this test, it can filter the VMFS on host and remove the host access.
See if this meets your requirements.

Thanks,
Ding Dong
