### ISSUE TITLE
Lun or Snapshot data not being get fetched, when try to do in Parallel

### ISSUE THREAD

**Issue by harbhajanrai** [emc-openstack/storops#192]
**Tried many connection**, to Unity Array using Storops, when tried restore Operation Lun using any snapshot, API **failed to get snapshot from array that is get_snap("xxx")** function failed and error message **TypeError: 'NoneType' object is not iterable**

Is there any limitation, on number of connection to array, which might be problem in this.
So, is there any way to get around this problem.

**Comment by DingDino** [comment]
@harbhajanrai 

Hi, harbhajanrai, sorry for the late response.
Did not reproduce the issue in my test lab.
Can you share more error message with the scripts if you still meet this problem?

**Comment by harbhajanrai** [comment]
@DingDino , 
Thanks for your response, not getting this error for now,
Closing this one, for now.
 Will get back to you, if any error arise with this context.
