### ISSUE TITLE
Failed to get NFS share for vnx

### ISSUE THREAD

**Issue by yugansh20** [emc-openstack/storops#200]
Hi

I am trying to get nfs shares from an array but it is throwing error.
This is my code - 
`
from storops import VNXSystem`
`vnx = VNXSystem('ip', 'user', 'password')`
`nfs = vnx.get_nfs_share()
`
I am able to get all other details of array. But for nfs it is throwing following error - 

ile "/usr/local/lib/python3.6/site-packages/storops/lib/common.py", line 51, in json
    return json.dumps(self.get_dict_repr(), indent=indent, sort_keys=True)
  File "/usr/local/lib/python3.6/site-packages/storops/lib/resource.py", line 270, in get_dict_repr
    items = [item.get_dict_repr(dec - 1) for item in self.list]
  File "/usr/local/lib/python3.6/site-packages/storops/lib/resource.py", line 261, in list
    self.update()
  File "/usr/local/lib/python3.6/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/resource/__init__.py", line 211, in update
    ret = super(VNXCliResourceList, self).update(data)
  File "/usr/local/lib/python3.6/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/resource/__init__.py", line 105, in update
    ret = super(VNXCliResource, self).update(data)
  File "/usr/local/lib/python3.6/site-packages/cachez.py", line 206, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/storops/lib/resource.py", line 227, in update
    data = self._get_raw_resource()
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/resource/nfs_share.py", line 100, in _get_raw_resource
    return self._cli.get_nfs_export(mover_id, self._path)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/nas_client.py", line 141, in func_wrapper
    check_invalid_data_mover=check_invalid_data_mover)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/nas_client.py", line 112, in request
    response = self._request(req, retry_patterns)
  File "/usr/local/lib/python3.6/site-packages/retryz/__init__.py", line 192, in func_wrapper
    ret = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/nas_client.py", line 91, in _request
    rsp_xml = self.xml_connector.post(req_xml)
  File "/usr/local/lib/python3.6/site-packages/storops/vnx/nas_client.py", line 71, in xml_connector
    self.host, self.username, self.password)
  File "/usr/local/lib/python3.6/site-packages/storops/connection/connector.py", line 113, in __init__
    self._login(host, user, password)
  File "/usr/local/lib/python3.6/site-packages/storops/connection/connector.py", line 119, in _login
    self.http_client.request(url, 'GET')
  File "/usr/local/lib/python3.6/site-packages/storops/connection/client.py", line 98, in request
    files=files_opener, **options)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='None', port=443): Max retries exceeded with url: /Login/?user=None&password=None&Login=Login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd88ab698d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='None', port=443): Max retries exceeded with url: /Login/?user=None&password=None&Login=Login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd88ab698d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by peter-wangxu** [comment]
Hi @yugansh20 
Please initialize the VNXSystem with additional parameters `file_username` and `file_password`.

**Comment by yugansh20** [comment]
Sorry for late reply...
Thank you.

I will try to do this and update here

**Comment by yugansh20** [comment]
It is still not working.

Do I need to pass mover and path value in get_nfs_share??

**Comment by yugansh20** [comment]
Also in the last line the host is also taken as None

**Comment by peter-wangxu** [comment]
```python
In [6]: vnx = VNXSystem('192.168.1.50', 'blockuser', 'blockpassword', file_username='fileuser', file_password='filepassword')

In [7]: vnx
Out[7]:
{
    "VNXSystem": {
        "agent_rev": "7.33.9 (1.35)",
        "existed": true,
        "hash": 8773361673073,
        "model": "VNX7600",
        "model_type": "Rackmount",
        "name": "APM00152904558",
        "revision": "05.33.009.3.135",
        "serial": "APM00152904558"
    }
}

In [8]: vnx.get_nfs_share()
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Out[8]:
{
    "VNXNfsShareList": []
}

In [9]: sg = vnx.get_sg(name='ubuntu-server7')

In [10]: sg
Out[10]:
{
    "VNXStorageGroup": {
        "alu_hlu_map": {
            "60": 117,
            "61": 259,
            "229": 58,
            "313": 49,
            "382": 128,
            "406": 133,
            "407": 100,
            "63930": 180,
            "63938": 212
        },
        "existed": true,
        "hash": 8773361760901,
        "hba_sp_pairs": {
            "VNXStorageGroupHBAList": [
                {
                    "VNXStorageGroupHBA": {
                        "hash": 5154832094190426664
                    }
                },
                {
                    "VNXStorageGroupHBA": {
                        "hash": -2230449996155285004
                    }
                },
            ]
        },
        "name": "ubuntu-server7",
        "shareable": true,
        "wwn": "E9:50:40:1B:71:DC:E6:11:8A:8D:98:9B:46:E6:FE:48"
    }
}

In [11]: sg.get
sg.get                      sg.get_fc_ports             sg.get_initiator_uids       sg.get_metric_value         sg.get_property_label
sg.get_alu_hlu_map          sg.get_hlu                  sg.get_iscsi_ports          sg.get_ports
sg.get_dict_repr            sg.get_index                sg.get_max_luns_per_sg      sg.get_preloaded_prop_keys

In [11]: sg.get
sg.get                      sg.get_fc_ports             sg.get_initiator_uids       sg.get_metric_value         sg.get_property_label
sg.get_alu_hlu_map          sg.get_hlu                  sg.get_iscsi_ports          sg.get_ports
sg.get_dict_repr            sg.get_index                sg.get_max_luns_per_sg      sg.get_preloaded_prop_keys

In [11]: sg.get
sg.get                      sg.get_fc_ports             sg.get_initiator_uids       sg.get_metric_value         sg.get_property_label
sg.get_alu_hlu_map          sg.get_hlu                  sg.get_iscsi_ports          sg.get_ports
sg.get_dict_repr            sg.get_index                sg.get_max_luns_per_sg      sg.get_preloaded_prop_keys

In [11]: sg.get_alu_hlu_map()
Out[11]:
{60: 117,
 61: 259,
 229: 58,
 313: 49,
 382: 128,
 406: 133,
 407: 100,
 63930: 180,
 63938: 212}


```

**Comment by peter-wangxu** [comment]
Can you please give me the output of `domain -list`?

like this: 

```ini
domain -list
Node:                 APMxxxxxxxxxxxxxx
IP Address:           192.168.1.53
Name:                 spb
Port:                 80
Secure Port:          443
IP Address:           192.168.1.52 (Master)
Name:                 spa
Port:                 80
Secure Port:          443

```

**Comment by yugansh20** [comment]
Hey...

I don't have access to storage array as I am just doing automation on top of it and not actually a storage expert.

I did this and it worked - 
>>> from storops import VNXSystem

>>>
>>> vnx = VNXSystem('10.0.0.0', 'sys', 'sysadmin' , file_username='sys', file_password='sys')

>>> vnx.name
security level is "undefined", update to "low".
'vnx5800-02cs1'

>>> vnx.domain
{
    "VNXDomainMemberList": [
        {
            "VNXDomainMember": {
                "existed": true,
                "hash": 1234,
                "ip_address": "10.2.22.9",
                "name": "Unisphere Central",
                "port": "80",
                "secure_port": "443"
            }
        },
        {
            "VNXDomainMember": {
                "existed": true,
                "hash": -1234,
                "ip_address": "10.5.12.8",
                "name": "SPB",
                "port": "80",
                "secure_port": "443"
            }
        },
        {
            "VNXDomainMember": {
                "existed": true,
                "hash": -9223363283926859,
                "ip_address": "10.1.12.2 (Master)",
                "name": "SPA",
                "port": "80",
                "secure_port": "443"
            }
        },
        {
            "VNXDomainMember": {
                "existed": true,
                "hash": -9223807457,
                "ip_address": "10.1.1.1",
                "name": "a-vnx5800-02",
                "port": "80",
                "secure_port": "443"
            }
        }
    ]
}

**Comment by peter-wangxu** [comment]
I know what's your problem now.
The domain did not contain control station ip.

to workaround this, use following below fetch file object:
```python
vnx._get_cs_ip = lambda : '<control station ip>'
```

**Comment by yugansh20** [comment]
Thank you.

This worked for me.
