### ISSUE TITLE
Unity snapshot - no way to configure multiple host_access

### ISSUE THREAD

**Issue by DanielDisisto** [emc-openstack/storops#205]
When attempting to set host access for a LUN snapshot, the `attach_to()` method will raise the following exception if there is already any existing host access configured for the snapshot -

```storops.exception.UnitySnapAlreadyPromotedException: The system was not able to promote a snapshot because it is already promoted. (Error Code:0x6000bdc)```

This reflects what is available in the Unisphere UI - once a snapshot is attached, the 'Attach to host' option is greyed out until it is first detached, after which new host access may be configured. As the method only accepts a single `host` argument, there is currently no way to configure multi-host access to a snapshot with storops, which the UI does support (as long as they're attached at the same time).

**Comment by peter-wangxu** [comment]
Fixed in https://github.com/emc-openstack/storops/pull/209
