### ISSUE TITLE
error on unity 300 for disk object

### ISSUE THREAD

**Issue by berger-anthony** [emc-openstack/storops#218]
Error ReferenceError: weakly-referenced object no longer exists

[root@B1LinCESP01 site-packages]# nagios-unity  -H 190.69.7.23 -u centreon -p "9999999999" battery
BATTERY OK: Total Batteries #2, Failed batteries: [] | 

[root@B1LinCESP01 site-packages]# nagios-unity  -H 190.69.7.23 -u centreon -p "999999999" dae
DAE OK: Total DAEs #1, Failed DAE(ID): [] | 
DAE 1 0: Power(curr/avg/max_if_not_empty)=167/167/167 watts, Temperature(curr/avg/max_if_not_empty)=19/19/20 degrees , Speed(curr/max)=12.0/12.0 GB
Exception ignored in: <bound method HTTPClient.__del__ of <storops.connection.client.HTTPClient object at 0x7f066bc59ac8>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/storops/connection/client.py", line 58, in __del__
    self.session.close()
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 707, in close
    for v in self.adapters.values():
  File "/usr/lib64/python3.4/_collections_abc.py", line 512, in __iter__
    for key in self._mapping:
  File "/usr/lib64/python3.4/collections/__init__.py", line 91, in __iter__
    curr = root.next
ReferenceError: weakly-referenced object no longer exists
Exception ignored in: <bound method HTTPClient.__del__ of <storops.connection.client.HTTPClient object at 0x7f066bc5b860>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/storops/connection/client.py", line 58, in __del__
    self.session.close()
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 707, in close
    for v in self.adapters.values():
  File "/usr/lib64/python3.4/_collections_abc.py", line 512, in __iter__
    for key in self._mapping:
  File "/usr/lib64/python3.4/collections/__init__.py", line 91, in __iter__
    curr = root.next
ReferenceError: weakly-referenced object no longer exists

**Comment by berger-anthony** [comment]
[root@B1LinCESP01 site-packages]# nagios-unity  -H 10.69.7.23 -u centreon -p "Bi0@ster;Centreon" system
SYSTEM OK: Name: B1UnityP01, MODEL: Unity 300, VERSION: 4.3.0 | 
ANTIVIRUS: Status=Enabled, Reason=None
BASE_OE_V4_0: Status=Enabled, Reason=None
CIFS: Status=Enabled, Reason=None
EMC_SUPPORT_ECOSYSTEM: Status=Enabled, Reason=None
ESA_ADAPTER: Status=Enabled, Reason=None
FAST_CACHE: Status=Enabled, Reason=None
FAST_VP: Status=Enabled, Reason=None
FIBRE_CHANNEL: Status=Enabled, Reason=None
FILE_SYSTEM_EVENTS: Status=Enabled, Reason=None
DATA_REDUCTION: Status=Enabled, Reason=None
IP_MULTI_TENANCY: Status=Enabled, Reason=None
ISCSI: Status=Enabled, Reason=None
LOCAL_COPIES: Status=Enabled, Reason=None
NFS: Status=Enabled, Reason=None
QUALITY_OF_SERVICE: Status=Enabled, Reason=None
REPLICATION: Status=Enabled, Reason=None
THIN_PROVISIONING: Status=Enabled, Reason=None
UNISPHERE: Status=Enabled, Reason=None
UNISPHERE_CENTRAL: Status=Enabled, Reason=None
VASA: Status=Enabled, Reason=None

**Comment by berger-anthony** [comment]
user centreon have administrator role

**Comment by berger-anthony** [comment]
[root@B1LinCESP01 site-packages]# nagios-unity --version
0.1.2
[root@B1LinCESP01 site-packages]# pwd
/usr/lib/python3.4/site-packages

**Comment by yong-huang** [comment]
Hi,

Did you try using Python 3.5 or Python 3.6? Seems this is Python 3.4 issue, please refer: https://github.com/requests/requests/issues/2303

**Comment by Murray-LIANG** [comment]
Close it due to no activities. Please re-open it if having any further issue or question.
