### ISSUE TITLE
The library keeps on running command getagent even after operation is complete

### ISSUE THREAD

**Issue by yugansh20** [emc-openstack/storops#228]
I am using storops to get basic storage array details.

Once I get the details, I see in logs the library still keeps on running following command at 1 minute interval - 
```
/opt/Navisphere/bin/naviseccli -h 1.1.1.1 -user username -password *** -scope 0 -np getagent
```
Do I need to close some connection??

**Comment by Murray-LIANG** [comment]
No. No need to close it. It works as a heartbeat to keep storops knowing which SP is alive, .etc.

**Comment by yugansh20** [comment]
I don't actually want the heartbeat check.

I just want to login collect some information and be done with it.

**Comment by Murray-LIANG** [comment]
You could use `system.stop_heart_beat()` to stop it.
But please note that after you stop the heart beat, some commands would fail.

More example:
```python
vnx = storops.VNXSystem(...)
...
vnx.stop_heart_beat()
```
