### ISSUE TITLE
I am able to get the IP subnet of the servers on which nfs can be mounted , but how can I get specific servers/ IPs where it is mounted

### ISSUE THREAD

**Issue by yugansh20** [emc-openstack/storops#231]
When I fo get_nfs_share for vnx array , it gives me subnets like 1.1.1.1/24 but can I get exact IP of the servers on which nfs is mounted??

**Comment by yong-huang** [comment]
Could you attach the codes you invoke get_nfs_share and the nfs share list here?

This is the nfs share list when I invoking system.get_nfs_share:
{"VNXNfsShareList": [{"VNXNfsShare": {"existed": true, "fs_id": 1348, "hash": 6077525, "mover_id": 1, "path": "/test_fs3", "read_only": false}}]}

There is no subnet info.

Actually I don't know which IP address do you want to get, the IP address in share export location path?

**Comment by Murray-LIANG** [comment]
Close it due to no activities. Please re-open it if having any further issue or question.
