### ISSUE TITLE
How to view Alert Messages on VNX

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#24]
Hi Team,
Can we read the alert messages in VNX via Storops ? Any way by which we can display the warning messages of VNX ? 

![alert](https://cloud.githubusercontent.com/assets/13348767/18728594/80bd4daa-806b-11e6-8c59-24ea75c04a57.PNG)

Thanks
Sunny

**Comment by jealous** [comment]
Hi Sunny,

I am closing this because storops cannot get this info.
This information is only available in GUI, not CLI.  So we cannot get it from storops.

**Comment by sunnyrarora** [comment]
Hi Jealous,
I understand you had closed this query. But just one last thing i wanted to higlight. 
Please go through this thread.
https://community.emc.com/thread/186315?start=0&tstart=0

By Any chance, can we get alert messages via 'getlog' command through naviseccli ?
And futher it can be filtered for "WARNING" Or "CRITICAL" Alert.

Thanks
Sunny

**Comment by jealous** [comment]
Hi Sunny,

We considered this option in another solution.  But generally, it doesn't work.  As the command stated, it's just log.  You could grab different events from log.  They are not necessary the alerts displayed in the GUI.
And there isn't any strict definition of what's logged and what's not.  
For example, the trigger of most alerts in GUI may logged.  But the cancel of the alert are probably not.
The creation of a RAID group LUN may be logged, but the delete isn't.
So it's not likely to assemble the view in GUI with the information retrieved from `getlog`.
