### ISSUE TITLE
Ability to specify HLU when using attach_alu

### ISSUE THREAD

**Issue by lingfish** [emc-openstack/storops#26]
Hi, would be real useful to be able to set the HLU when using attach_alu against a storage group.

I use boot LUNs, and host-based storage groups, where the HLUs all need to match.

**Comment by jealous** [comment]
Hi Lingfish,

I added an optional parameter on `VNXStorageGroup.attach_alu`.  You could use named parameter `hlu` to set the hlu ID.

Let me know if it works.  Thanks.

**Comment by lingfish** [comment]
Thanks heaps, will try in the next week.
