### ISSUE TITLE
Modifications of SNMP data not available through storops

### ISSUE THREAD

**Issue by thedreadpirateeric** [emc-openstack/storops#269]
A very handy configuration would be the SNMP data.

`/apidocs/classes/alertConfigSNMPTarget.html`

"/api/types/alertConfigSNMPTarget/instances"

Is this a feature that can be added?

**Comment by DingDino** [comment]
Hi, @thedreadpirateeric ,

You want to 'modify' the Unity alert info?
Can you give us more background about this feature?

We need evaluate the effort based on that.

**Comment by thedreadpirateeric** [comment]
We are a hosting provider and deploy many of the unity arrays all the time. We are trying to automation the full lifecycle for the infrastructure as much as possible and abstract out many of the changes. If we have to change the SNMP settings after they are stood up we would need to make that change on hundreds of Unity arrays.

**Comment by DingDino** [comment]
@thedreadpirateeric 
We will implement this feature. 
Add Unity supported operations:
- Collection query, 
- Instance query, 
- Create, 
- Delete, 
- Modify

**Comment by DingDino** [comment]
@thedreadpirateeric 

We will build a simple SNMP manager server to test this feature.
Do you have more test SNMP managers, so that you can help us to verify this feature?
To see if this matches your requirement before we release it.

FYI.

**Comment by DingDino** [comment]
implemented, close this issue
