### ISSUE TITLE
Getting list of Lun Names for Particular pool

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#27]
Hi Team,
Is there any direct method by which i can get all the Luns which belongs to particular pool.
I am using below method for now, but this gives me detailed ouput of luns.

```
>>>vnx = VNXSystem('10.xx.xx,xx', 'user', 'password')
>>>luns = vnx.get_lun()
>>>luns2 =  list(luns)
>>>type(luns2)
<type 'list'>
>>>len(luns2)   <- This gives me number 200+ luns which belongs to all the pools.
>>>luns3=filter(lambda x: x.pool_name=="Pool_1", luns2)
```
Variable luns3 gives me a big output with all details of around 12 luns which belongs to this pool "Pool_1". But i only need lun names.
Is there any direct way to achieve for getting list of luns which belongs to the particular pool ?

Thanks
Sunny

**Comment by jealous** [comment]
Hi Sunny,

Sorry for the delayed response.  We are in holiday these days.
Once you have a pool instance, you could get the luns under that pool with:
``` python
pool.lun_list
```
This property contains the list of LUN instances under that pool.  You could retrieve the names of the lun in that list by access the property directly from the list.  That will be:
``` python
pool.lun_list.name
```
Let me know if it does the trick.

**Comment by sunnyrarora** [comment]
Hey Cedric/Jealous,
That worked for me.

Thanks again for the help.
Regards

Sunny
