### ISSUE TITLE
general question regarding lunZ

### ISSUE THREAD

**Issue by kdada1234** [emc-openstack/storops#271]
Anyway to disable LUNz or set the Host ID zero( -arraycommpath 0 ) to the first LUN for cinder driver?

**Comment by Murray-LIANG** [comment]
No. The `-arraycommpath` is not supported to set via storops VNX.
And Storops VNX skips the hlu 0 when attaching alu, that is, hlu 0 is never used via storops VNX.
You could check it in source codes: https://github.com/emc-openstack/storops/blob/develop/storops/vnx/resource/sg.py#L279
