### ISSUE TITLE
Storops installation on Centos 6 with python 3.6

### ISSUE THREAD

**Issue by cnbscience** [emc-openstack/storops#272]
I was trying to install storops on centos 6 with python 3.6. I am able to install it on my Mac which has python 3.6. I am not sure why. Here is the stack trace 

**>>> import storops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/act/bin/virtualenvs/purestorage/lib/python2.7/site-packages/storops/__init__.py", line 21, in <module>
    from storops.lib.thinclone_helper import TCHelper  # noqa
  File "/act/bin/virtualenvs/purestorage/lib/python2.7/site-packages/storops/lib/thinclone_helper.py", line 20, in <module>
    from persistqueue import PDict
ImportError: cannot import name PDict**

I have also installed pdict separately , but no use. the site packages directory has PDict. 

This is my pip freeze
bitmath==1.3.3.1
cachez==0.1.2
certifi==2019.6.16
chardet==3.0.4
idna==2.8
pdict==1.4
persist-queue==0.4.2
python-dateutil==2.8.0
PyYAML==5.1.1
requests==2.21.0
retryz==0.1.9
six==1.12.0
storops==1.2.0
urllib3==1.24.3

**Comment by Murray-LIANG** [comment]
Do you mean you installed storops under python36? But the error message shows you are using py27 in a virtual env. Could you share more about your python env, including python version, virtual env used, and how you installed the storops in the virtual env. etc.?

And it's not related to the lib `pdict`. The `PDict` is released with `persist-queue`. And I double-confirmed that the `persist-queue` you installed (version 0.4.2) includes the `PDict`. So it should not be a `ImportError: cannot import name PDict` issue if you installed `persist-queue`.

**Comment by cnbscience** [comment]
Hi Murray, 
Thanks for the quick response, I think I have figured out the problem, PDict has a dependency on sqlit3, and the sqlite3 is not properly configured n my system. The import error is just a symptom of improper sqlite3 configuration. 
I have one more question on CBT for snapshots, I was looking at storops  library and I din't see an API which could give be block differences between 2 snapshots. Correct me if I am wrong about this.

**Comment by Murray-LIANG** [comment]
No. There is no API in storops to know the block differences between 2 snapshots. Storops is used to manage Unity and VNX storage systems. AFAIK, there is no API exported by Unity to query the block differences.
