### ISSUE TITLE
consistency group error

### ISSUE THREAD

**Issue by cnbscience** [emc-openstack/storops#273]
I was trying out consistency group API. I can create a consistency group but I cannot add a lun to the group using "add_lun{*lun_list) API. 

I am getting the following error : 

In [85]: cg.add_lun(tlist)
/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
---------------------------------------------------------------------------
UnityPolicyIncorrectRequestBodyError      Traceback (most recent call last)
<ipython-input-85-005fe3a8a789> in <module>()
----> 1 cg.add_lun(tlist)

/anaconda3/lib/python3.6/site-packages/storops/unity/resource/cg.py in add_lun(self, *lun_list)
    177 
    178     def add_lun(self, *lun_list):
--> 179         return self.modify(lun_add=lun_list)
    180 
    181     def remove_lun(self, *lun_list):

/anaconda3/lib/python3.6/site-packages/storops/unity/resource/cg.py in modify(self, name, description, is_repl_dst, snap_schedule, tiering_policy, is_compression, hosts, lun_add, lun_remove, host_add, host_remove, lun_modify)
     88                                 self.get_id(), 'modifyConsistencyGroup',
     89                                 **req_body)
---> 90         resp.raise_if_err()
     91         return resp
     92 

/anaconda3/lib/python3.6/site-packages/storops/unity/resp.py in raise_if_err(self)
    129         if self.has_error():
    130             ex_clz = get_rest_exception(self.error_code)
--> 131             raise ex_clz(self.error)
    132 
    133     @property

UnityPolicyIncorrectRequestBodyError: Request body is not correct. There may be duplicate parameters, wrong parameter name. Please refer to API documentation page and ensure the body is correct. (Error Code:0x7d13035)

I am not sure if this is something anyone else have faced, or am I doing something wrong while adding a lun to the consistency group.

**Comment by Murray-LIANG** [comment]
What is the `tlist` passed into `cg.add_lun`? You should unpack it before passing to `cg.add_lun` like `cg.add_lun(*tlist)`.

**Comment by cnbscience** [comment]
I have tried that as well and I am having the same result. I would like to know if you guys have tried it on your sandbox , if it works, could you provide me more details.

**Comment by Murray-LIANG** [comment]
Yes, we tried.

```python
Python 3.6.8 (default, Jun 11 2019, 01:16:11) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import storops
>>> u = storops.UnitySystem('10.245.101.39', 'admin', 'Password123!')

>>> cg = u.get_cg(name='test_cg_name')
# Already having 4 luns in the cg.
>>> cg
{
    "UnityConsistencyGroup": {
        ... ...
        "luns": {
            "UnityLunList": [
                {
                    "UnityLun": {
                        "hash": -9223363274629303478,
                        "id": "sv_1546"
                    }
                },
                {
                    "UnityLun": {
                        "hash": -9223363274625488787,
                        "id": "sv_1544"
                    }
                },
                {
                    "UnityLun": {
                        "hash": 8762225417017,
                        "id": "sv_1545"
                    }
                },
                {
                    "UnityLun": {
                        "hash": -9223363274629358746,
                        "id": "sv_1547"
                    }
                }
            ]
        },
... ...

>>> lun1 = u.get_lun(name='lun_7')
>>> lun2 = u.get_lun(name='lun_8')
>>> lun_to_add = [lun1, lun2]
>>> cg.add_lun(*lun_to_add)

# Two new luns added to the cg.
>>> cg.update()
{
    "UnityConsistencyGroup": {
        ... ...
        "luns": {
            "UnityLunList": [
                {
                    "UnityLun": {
                        "hash": -9223363274629305084,
                        "id": "sv_1549"
                    }
                },
                {
                    "UnityLun": {
                        "hash": -9223363274629304986,
                        "id": "sv_1546"
                    }
                },
                {
                    "UnityLun": {
                        "hash": -9223363274629304874,
                        "id": "sv_1544"
                    }
                },
                {
                    "UnityLun": {
                        "hash": 8762225470868,
                        "id": "sv_1545"
                    }
                },
                {
                    "UnityLun": {
                        "hash": 8762225470875,
                        "id": "sv_1595"
                    }
                },
                {
                    "UnityLun": {
                        "hash": 8762225470959,
                        "id": "sv_1547"
                    }
                }
            ]
        },
... ...
```
