### ISSUE TITLE
storops incompatible with openstack upper-constraints.txt

### ISSUE THREAD

**Issue by prometheanfire** [emc-openstack/storops#276]
Your exclusion of requests 2.22.0 makes storops incompatible with openstack gate.  upper-constraints is set to use 2.22.0.

It was excluded in the following commit

https://github.com/emc-openstack/storops/commit/5d82172fba84feb67321fb6bd85d56b7424e58ce

**Comment by Murray-LIANG** [comment]
Thank you for reporting this, @prometheanfire.
I'll remove this constraint.

**Comment by prometheanfire** [comment]
thanks, once it's removed and a release is made we should be good to include the update in our constraints

**Comment by Murray-LIANG** [comment]
Version v1.2.1 released.
