### ISSUE TITLE
Unity:  EnclosureTypeEnum missing

### ISSUE THREAD

**Issue by matmb-cld** [emc-openstack/storops#284]
Hello,
I have an issue when getting dpe information from a 480F Unity array (version 5.0).

>>> unity.get_sp(id='spa').parent_dpe
....
File "/home/mat/Virtualenv/xymon_cloud/local/lib/python2.7/site-packages/storops/lib/common.py", line 194, in _raise_invalid_value
    raise storops.exception.EnumValueNotFoundError(msg)
storops.exception.EnumValueNotFoundError: 38 is not a valid value for EnclosureTypeEnum

 And I solved this issue by simply adding the following variable
 SCORP_12G_SAS_DPE = (38, '25 Drive 12G DPE')
To the class class EnclosureTypeEnum(UnityEnum) in the file storops/unity/enums.py 

I've found this Enclosure Type in the document: Unisphere Management REST API
Reference Guide

Regards
Mathieu

**Comment by yong-huang** [comment]
Thanks for the report.
Fixed in review [[GH-284] Unity: add 'SCORP_12G_SAS_DPE' in EnclosureTypeEnum](https://github.com/emc-openstack/storops/pull/285).

**Comment by matmb-cld** [comment]
Thank you for your quick answer.
