### ISSUE TITLE
Host WWNs details is missing from storage group output

### ISSUE THREAD

**Issue by deepakdevpro** [emc-openstack/storops#287]
Hi,

First of all a big thank you for your team to build this module for VNX. It eases a lot of pain in coding all functionality from scratch.

I am building a Storage to Host map table in following format:
FrameSPName, SG-Name, Host-WWNs, SP_Group, SPGroup-WWNs

I have successfully pulled out information for all except host wwns.

I am not able to get HBA UID details from available options.

HBA/SP Pairs:

  HBA UID                                                               SP Name  SPPort
  -------                                                                    -------     ------
  50:01:43:80:13:0F:49:4F:**50:01:43:80:13:0F:49:4E**  SP B          9
  50:01:43:80:13:0F:4B:73:**50:01:43:80:13:0F:4B:72**   SP B         11
  50:01:43:80:13:0F:4B:73:**50:01:43:80:13:0F:4B:72**   SP A         9
  50:01:43:80:13:0F:49:4F:**50:01:43:80:13:0F:49:4E**   SP A         11

Can you please help me if there is way available to pull this info out.

Thank you in advance!

**Comment by DingDino** [comment]
Hi,

First you need make sure there is data in HBA/SP Pairs:.

I made some test, and we can get the result like below:
....
(u'20:00:00:90:FA:53:4C:D1:10:00:00:90:FA:53:4C:D1', u'SP A', u'11')
(u'20:00:00:90:FA:53:4C:D1:10:00:00:90:FA:53:4C:D1', u'SP A', u'7')
(u'iqn.1993-08.org.debian:01:e3b24b2eb2d3', u'SP B', u'12')
(u'20:00:00:90:FA:53:4C:D1:10:00:00:90:FA:53:4C:D1', u'SP B', u'11')
....

The code is here:

    vnx = VNXSystem('10.10.10.10', 'user_name', 'password')
    storage_group = vnx.get_sg('test_name')
    hba_sp_pairs = storage_group.hba_sp_pairs
    for sg_hba in hba_sp_pairs:
        print sg_hba.hba

Hope this can help you.


BR,
Ding Dong

**Comment by deepakdevpro** [comment]
The expansion of functionality is much more than I discovered it seems. This trick did work for me.

def get_hostwwnspporttable(sgname):
	maplist = []
	stggrp = vnx.get_sg(name=sgname)
	for hba_port in stggrp.hba_sp_pairs:
		hostwwn = hba_port.hba[0]
		spname = hba_port.hba[1]
		spportid = hba_port.hba[2]
		host_name = hba_port.host_name
		maplist.append((hostwwn, spname, spportid, host_name))
	return maplist

>>> get_hostwwnspporttable('myhostname')
[('20:00:00:90:FA:3D:7E:44:10:00:00:90:FA:3D:7E:44', 'SP B', '11', 'myhostname'), 
('20:00:00:90:FA:3D:7F:52:10:00:00:90:FA:3D:7F:52', 'SP A', '11', 'myhostname'), 
('20:00:00:90:FA:3D:7E:44:10:00:00:90:FA:3D:7E:44', 'SP A', '9', 'myhostname'), 
('20:00:00:90:FA:3D:7F:52:10:00:00:90:FA:3D:7F:52', 'SP B', '9', 'myhostname')]

Thank you so much Ding Dong.
