### ISSUE TITLE
Unable to change SP of Unity NAS Server

### ISSUE THREAD

**Issue by dkmonaghan** [emc-openstack/storops#299]
Hello,

We're trying to use storops to change the SP of a NAS server on a Unity 400 appliance, however nothing seems to be working. I've trawled through the tests and example code, and the closest thing I can see is in `test_lun.py` where the SP is set:

https://github.com/emc-openstack/storops/blob/b2e948a27ed960c303d696422500e6829a08d1c8/storops_test/unity/resource/test_lun.py#L100

I've tried doing this with a NAS server with no luck.

`
In [106]: nas.modify(sp=target_sp)
`
`
Out[106]: <storops.unity.resp.RestResponse at 0x7f8e7645f780>
`

Where `nas` is a UnityNasServer object and `target_sp` is a UnityStorageProcessor object. I've checked all the details multiple times; the correct SP is definitely selected as well as the correct NAS server, but nothing happens.

Any ideas? Thank you!

Using storops 1.2.3

**Comment by DingDino** [comment]
@dkmonaghan 

Hi, checked the scripts:
storops/unity/resource/lun.py 
storops/unity/resource/nas_server.py.

There is no function support **modify**  in nas_server.py. Means storops doesn't support modify for NAS server. 
We can create a feature for this and try to implement it.
But it's close to our Spring festival. Cannot guarantee when you can get it.

**Comment by dkmonaghan** [comment]
@DingDino Thanks very much for your quick reply. Looking forward to testing it once available :)

**Comment by DingDino** [comment]
@dkmonaghan 

Hi, I made a quick test in branch **unity_modify_nas** . With these new codes, you can use the modify method to change SP of NAS server.
[](https://github.com/emc-openstack/storops/tree/unity_modify_nas)

You can try it first and let me the results.

**Comment by dkmonaghan** [comment]
Thank you for doing that so quickly @DingDino! We have tested the new branch this morning and changing SP works as expected :)

Thank you!
