### ISSUE TITLE
Unable to fetch NFS Host Access List on Unity

### ISSUE THREAD

**Issue by dkmonaghan** [emc-openstack/storops#302]
Trying to fetch the list of hosts who have access to an NFS share, but storops keeps returning an empty list.

Using storops version 1.2.3, latest version of Unity 400 OS (v5.0.2.0.5.009)

Testing on a share where three hosts have "Read/Write, allow root" access. Using the following code:

```
nfs = unity.get_nfs_share(_id='NFSShare_50')
nfs.update()
pprint(nfs.root_access_hosts)
```
Result from the above is just:
```
None
```

I've tried a few things and can't see why this doesn't work. I've looked through the source code for test_nfs_share and it seems like the tests there access lists of hosts this way.

Any pointers, please? :)  Thanks!

**Comment by DingDino** [comment]
Hi, @dkmonaghan 

You can trying to print the 'nfs', and seek from the result.
There is something like '**no_access_hosts**' property of nfs you can use to get the Host Access List.
Although the property name is kind confuse me also.

Thanks,
Ding Dong

**Comment by dkmonaghan** [comment]
Hi @DingDino 

Thanks for your quick reply.

At present we aren't using the 'Hosts' feature (I believe this is called Advanced Host Management?), we are simply adding IP addresses in directly to NFS shares.

We use the option "By entering a comma separated list of hosts" to add hosts to NFS share access.

After some digging into the storops API I can see it's only possible to add hosts to NFS shares if they are defined as 'Host' objects on Unity itself.

Is there any way for storops to use the older method of host access on NFS shares? Or does the API only allow for Advanced Host Management?

**Comment by DingDino** [comment]
@dkmonaghan ,
What do you mean the **older method** , we don't support the old method in storops if you are saying using "By entering a comma separated list of hosts". 
We can add an enhancement for it.

Currently in storops, the IPs need to be created to Hosts then add to NFS share access.

**Comment by dkmonaghan** [comment]
Thanks again for your quick reply 😊 That makes sense. We’ve just gone through and switched over all our NFS access lists to use ‘Hosts’ and storops is displaying them as expected now.

 

I think the enhancement to support the other method of adding hosts in storops would be a good feature

**Comment by yong-huang** [comment]
@dkmonaghan Seems the commit https://github.com/emc-openstack/storops/commit/04374789075b43521c489af0dd34a01f9475778a already meet your requirement.
