### ISSUE TITLE
Managing quotas / quota trees on Unity

### ISSUE THREAD

**Issue by dkmonaghan** [emc-openstack/storops#311]
Hello,

We're running a Unity 400 appliance and would like to use storops to manage fileshare quotas, specifically quota trees. Is this functionality implemented into storops at the moment? I've searched the documentation and source code and couldn't find any reference to this functionality. 

Is this something that could be implemented?

Many thanks.

**Comment by Murray-LIANG** [comment]
No. Storops doesn't support treequota currently. The team is busy with other priority features. Leave this issue open as a request for features.

**Comment by dkmonaghan** [comment]
@Murray-LIANG Thank you for your quick reply. Looking forward to the feature once it is available.

**Comment by dkmonaghan** [comment]
Hello @Murray-LIANG 

Hope you are well.

Just wondering if there is any progress on this?

Best,
Dan

**Comment by Murray-LIANG** [comment]
Sorry, have no progress on this. We will plan it into next releases.

**Comment by yong-huang** [comment]
The feature implemented in https://github.com/emc-openstack/storops/commit/5bac4688ba775fb90bfb6d6e4f97cb5da608ebfc
