### ISSUE TITLE
Unity: add dedup support

### ISSUE THREAD

**Issue by Murray-LIANG** [emc-openstack/storops#323]
Add `Advanced Deduplication` support for Unity LUNs, and then Unity OpenStack Cinder driver would leverage it to create volumes with deduplication enabled.

**Comment by jsutton** [comment]
@yong-huang I see there are some commits that reference this issue, but they do not belong to a branch that exists. There is also this branch https://github.com/emc-openstack/storops/tree/advanced-dedup that appears to have similar work applied to it. Is this work ready to test? If so, I may be in a position to help test. If not, are there any known issues that need to be resolved?

**Comment by yong-huang** [comment]
@jsutton Yes, this branch is ready for the test, there is only one comment I need to address, but I don't have time to address it now. If you find any issues, feel free to file bugs or add comments, thanks.

**Comment by yong-huang** [comment]
Implemented in v1.2.8
