### ISSUE TITLE
Add simple request for health of disk array (VNX and Unity)

### ISSUE THREAD

**Issue by gszurek** [emc-openstack/storops#326]
Hi,
For VNX this could be output from:
- NaviSECCli.exe -address <addr> -User <user> -Password <pass> -Scope 0 faults -list,
and for UNITY:
- https://<addr>/api/types/system -> 
{"state":2,"name":"health","type":"health","description":"Health information for the system, as defined by the health resource type.","displayValue":"health"}

Thank you!

**Comment by Murray-LIANG** [comment]
## VNX
We are not going to add new features for VNX.

## Unity
You could use this:
```python
u = storops.UnitySystem('<ip>', '<username>', '<password>')
print(u.health)
```

**Comment by gszurek** [comment]
Hi Murray,
Thank you for the hint (and for a whole good work with this library). I
didn't use ".health" before, because I couldn't find it in documentation on
https://github.com/emc-openstack/storops/blob/master/README.rst. Do you
have some document, where I can find all supported futures?
Btw, this syntax doesn't work for me: *u = storops.UnitySystem('<ip>',
'<username>', '<password>')*. I must use *u = UnitySystem('<ip>',
'<username>', '<password>' *(without *storops* word)*. *Is it normal?
ps. Have you any plans for EMC Recover Point?

Best regards
Grzegorz Szurkało


wt., 20 paź 2020 o 04:33 Murray LIANG <notifications@github.com> napisał(a):

**Comment by Murray-LIANG** [comment]
Sorry, we didn't have a document covering everything of storops. What we have are the README and the source code.

Using `storops.UnitySystem` or `UnitySystem` depends on what you import in your source code.
If you `import storops`, then `storops.UnitySystem`. If you `from storops import UnitySystem`, then `UnitySystem`.

We have no plan for RecoverPoint.

**Comment by gszurek** [comment]
Tanks a lot! Everything clear.
