### ISSUE TITLE
Label typo in Unity parser_configs.yaml

### ISSUE THREAD

**Issue by bmcfeeters** [emc-openstack/storops#328]
label: harbestState

https://github.com/emc-openstack/storops/blob/d78a72dbf9d0b8b812d794077200bc3dfd97174e/storops/unity/parser_configs.yaml#L167

**Comment by yong-huang** [comment]
'label: harvestState' already exist, so will remove 'label: harbestState', thanks for the reporting.

https://github.com/emc-openstack/storops/blob/d78a72dbf9d0b8b812d794077200bc3dfd97174e/storops/unity/parser_configs.yaml#L191

**Comment by yong-huang** [comment]
Fixed in commit: https://github.com/emc-openstack/storops/commit/04374789075b43521c489af0dd34a01f9475778a
