### ISSUE TITLE
How to get the IP's of NAS_servers?

### ISSUE THREAD

**Issue by nehatomar12** [emc-openstack/storops#329]
nas_servers = conn.get_nas_server()

we get the information of nas_servers
How can we get the IP's associated Nas_servers?

**Comment by Murray-LIANG** [comment]
```python
for nas_server in nas_servers:
    interfaces = nas_server.file_interface
    ip_addresses = [e.ip_address for e in interfaces]
```
`nas_server.file_interface` will return a list of file interfaces. Then each interface has a property named `ip_address`.

**Comment by nehatomar12** [comment]
@Murray-LIANG 
Thanks, It is working

Can you tell me how can I get information about the protocols enabled on the Nas Servers?

**Comment by Murray-LIANG** [comment]
If the nas server enabled NFS, there is at least one NFS server whose nas server is that nas server.
```python
nas_server = conn.get_nas_server()[0]
nfs_servers = [e for e in conn.get_nfs_server() if e.nas_server.id == nas_server.id]
nfs_enabled = len(nfs_servers) != 0
```
