### ISSUE TITLE
Query on filesystem and NFS/SMB Share mapping

### ISSUE THREAD

**Issue by mukeshguptakc** [emc-openstack/storops#339]
Hi We are working on proliferating EMC Unity, we wanted know mapping between Filesystem and the NFS/SMB share is that 1:1 or Can there be Multiple Shares on same Filesystem ??
And have access to specific part of filesystem ...

As the Share would be visible for Read/Write access
But for Protection we would take snapshots on Storage resource(Filesystem) mapped to that share.

If Yes, 
How can we avoid duplicate snapshot copies when we protect multiple shares which would point to same Filesystem.

**Comment by Y0NG-WANG** [comment]
Hi,
Thank you for the asking. But the developer and maintainer from storops might not answer this question accurately. We suggest that you could get the answer from Unity support service. I suppose that you have the Unity support account. They could answer the product questions more accurately.

**Comment by mukeshguptakc** [comment]
Thank you, @Y0NG-WANG!

we would raise a support ticket with Unity and ask for the detail understanding.
Meanwhile, can you atleast let us know if we can actually create more than 1 share on a Filesytem, as per know from UI we are restricted..

This query could help us in mapping 1:1 between Filesytem and exported NFS/SMB shares.

**Comment by yong-huang** [comment]
Hi,

Filesystem and share is 1:1 mapping, you can't create more than 1 share on a Filesystem.

**Comment by mukeshguptakc** [comment]
Hi @yong-huang,

Thanks, for resolution and help on the thread.
Yes, we received the same response from the EMC Unity Support that Filesystem and Share has 1:1 Mapping.
