### ISSUE TITLE
Query on filesystem snapshot diff capabilities

### ISSUE THREAD

**Issue by mukeshguptakc** [emc-openstack/storops#340]
Hi We are working on proliferating EMC Unity.
We are exploring the APIs in which we would be able to fetch the snapshot difference between two Snapshots.

Can you please help me in do know whether do we support the EMC Unity NFS/SMB Snapshot diff of Filesystem.

If yes, Can you point to the API's and test/trail scripts for the same.

**Comment by Y0NG-WANG** [comment]
Hi,
Similar to last question. Thank you for the asking. But the developers and maintainers from storops might not answer this question accurately. We suggest that you could get the answer from Unity support service. I suppose that you have the Unity support account. They could answer the product questions more accurately.

**Comment by mukeshguptakc** [comment]
Thank you, @Y0NG-WANG!

we would raise a support ticket with Unity and ask for the same.
Meanwhile, can you atleast point me or redirect me to APIs related to snapshot diff, so we could do initial exploration till support channel is established with DELL EMC Unity.

**Comment by yong-huang** [comment]
Hi,

NFS/SMB/Filesystem Snapshot diff is not supported, only LUN snapshot diff is supported, you could double-check with the Unity support service.

**Comment by mukeshguptakc** [comment]
Hi @yong-huang,

Thanks, for resolution and help on the thread.
Yes, we received the same response from the EMC Unity Support that the Snapshot diff APIs are available for LUN Asset and not for NFS/SMB/Filesystem.
