### ISSUE TITLE
Issue storage pool type enum

### ISSUE THREAD

**Issue by Pavan-Mudunuri** [emc-openstack/storops#358]
While calling StoragePoolTypeEnum from enum module is returning dynamic in place of traditional and traditional in place of dynamic we have cross verified  it with array documentation and it appears the enum value which is being returned is not as per the documentation
![Screenshot (2)](https://user-images.githubusercontent.com/93370979/154911586-98ad0da5-0ffb-47d4-ba50-b56096ec667e.png)
![Screenshot (4)](https://user-images.githubusercontent.com/93370979/154911590-5ecc2655-7b8b-441b-8f93-0578ae4ae90d.png)
Can you please look into the issue ?
Thanks
Pavan

**Comment by yong-huang** [comment]
Thanks for the reporting, will fix it.

**Comment by yong-huang** [comment]
Fixed in https://github.com/emc-openstack/storops/pull/359, close it.
