### ISSUE TITLE
CAVA support on NAS Server

### ISSUE THREAD

**Issue by kuttattz** [emc-openstack/storops#365]
As part of customer request we have to support below operation on NAS server

- enable/disable/view CAVA on NAS Server.
- Upload/edit/download antivirus configuration.
 
![image](https://user-images.githubusercontent.com/91727659/159456166-db8dc042-2057-4e55-8f7f-6d04854ff453.png)

As per our observation we could not find any support from SDK. Can you please help us with adding the support for the CAVA?
Please let us know about your plan for the same

**Comment by yong-huang** [comment]
Supports CAVA enable/disable and file download/upload in https://github.com/emc-openstack/storops/pull/373, close this ticket.
