### ISSUE TITLE
Support for modify operation and few additional fields on NFS server

### ISSUE THREAD

**Issue by kuttattz** [emc-openstack/storops#366]
As part of customer request we are looking into supporting modify operation on NFS server. As per our observation we could not find any support from SDK.
Also "credentialsCacheTTL" and "nfsv3Enabled" attributes were missing in the NFS server class.

![image](https://user-images.githubusercontent.com/91727659/159458319-d57eece2-b335-492a-9199-38b2abbac828.png)

Can you please help us with adding the support for modify operation and also by  adding the attributes "credentialsCacheTTL" and "nfsv3Enabled" to NFS server ?
Please let us know about your plan for the same

**Comment by yong-huang** [comment]
Supports NFS server modify in https://github.com/emc-openstack/storops/pull/373, close this ticket.
