### ISSUE TITLE
Add Unity Disk total latency and queue length support.

### ISSUE THREAD

**Issue by jealous** [emc-openstack/storops#62]
Add metric `total_latency_ms` and `queue_length` for unity disk.
Required metrics:
* sp.\*.physical.disk.\*.busyTicks
* sp.\*.physical.disk.\*.sumArrivalQueueLength
* sp.\*.physical.disk.\*.reads
* sp.\*.physical.disk.\*.writes
* sp.\*.physical.coreCount

Formula:
* Total calls for each SP: 
  >delta(reads) + delta(writes)
* Total Latency for each SP: 
  >((delta(busyTicks) * (delta(sumArrivalQueueLength)/(total calls))) / (total calls)) / coreCount
* Total Latency (ms): 
  >((spa total latency) * (spa total calls) + (spb total latency) * (spb total calls)) / ((spa total calls) + (spb total calls)) / 1000
* Queue Length for each SP: 
  >(delta(sumArrivalQueueLength)/(total calls)) / coreCount
* Average Queue Length (count): 
  >((spa Queue Length) * (spa total calls) + (spb Queue Length) * (spb total calls)) / ((spa total calls) + (spb total calls))

**Comment by yong-huang** [comment]
In [r0.5.2](https://github.com/emc-openstack/storops/releases/tag/r0.5.2), total queue_length and response_time for Disk are implemented.
