### ISSUE TITLE
Add `total_latency_ms` and `queue_length` metric for Unity LUN.

### ISSUE THREAD

**Issue by jealous** [emc-openstack/storops#64]
Add Unity LUN metrics `total_latency_ms` and `queue_length`.

Related paths:
* sp.\*.storage.lun.\*.totalIoTime
* sp.\*.storage.lun.\*.currentIOCount
* sp.\*.storage.lun.\*.busyTime
* sp.\*.storage.lun.\*.idleTime
* sp.\*.storage.lun.\*.reads
* sp.\*.storage.lun.\*.writes

Formula:
* Total latency (ms):
>  ((spa totalIoTime) + (spb totalTime)) / ((spa total calls) + (spb total calls))/1000
* Average Queue Length for each SP (count):
>  delta(currentIOCount) * (delta(busyTime)/(delta(idleTime) + delta(busyTime)))
* Average Queue Length (count): 
> ((spa Queue Length) * (spa total calls) + (spb Queue Length) * (spb total calls)) / ((spa total calls) + (spb total calls))

**Comment by yong-huang** [comment]
In [r0.5.2](https://github.com/emc-openstack/storops/releases/tag/r0.5.2), total queue_length and response_time for LUN are implemented.
