### ISSUE TITLE
Add metrics for Unity Virtual Volume.

### ISSUE THREAD

**Issue by jealous** [emc-openstack/storops#65]
Add following metrics for Unity Virtual Volume.
Note that virtual volume has two implementations: block & file.
The path and calculation is different for different kind of virtual volume.
* read_iops
* write_iops
* read_mbps
* write_mbps
* total_latency_ms

Related paths:
* block based vvol:
  * sp.\*.storage.vvol.block.\*.reads
  * sp.\*.storage.vvol.block.\*.writes
  * sp.\*.storage.vvol.block.\*.totalIoTime
  * sp.\*.storage.vvol.block.\*.reads
  * sp.\*.storage.vvol.block.\*.readBlocks
  * sp.\*.storage.vvol.block.\*.writes
  * sp.\*.storage.vvol.block.\*.writeBlocks
* file based vvol:
  * sp.\*.storage.vvol.file.\*.readIoTime
  * sp.\*.storage.vvol.file.\*.reads
  * sp.\*.storage.vvol.file.\*.writeIoTime
  * sp.\*.storage.vvol.file.\*.writes
  * sp.\*.storage.vvol.file.\*.reads
  * sp.\*.storage.vvol.file.\*.readBytes
  * sp.\*.storage.vvol.file.\*.writes
  * sp.\*.storage.vvol.file.\*.writeBytes

Formula:
* Total calls for each SP:
> delta(reads) + delta(writes)
* totalIoTime for each SP
> delta(readIoTime) + delta(writeIoTime)
* Total Latency:
> ((spa totalIoTime) + (spb totalTime)) / ((spa total calls) + (spb total calls))/1000

**Comment by yong-huang** [comment]
Won't support it, close this ticket.
