### ISSUE TITLE
Add file count limit for persisted metric csv files.

### ISSUE THREAD

**Issue by jealous** [emc-openstack/storops#66]
The persisted metrics csv file now saves to the same file for each resource kind.  This enhancement has two requirement:
* Open a new persisted csv file when the file size reaches limit.
* Limit the maximum number of csv files per each resource kind.  Remove the oldest one if we reach the limit.

Both limits should be configurable from `UnitySystem`.

**Comment by yong-huang** [comment]
Won't support it, close this ticket.
