### ISSUE TITLE
How to get Host List for VNX ?

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#7]
Hi Team,
Is there any way by which i can get Host lists and allocated luns of VNX through Storops?

Thanks
Regards

Sunny

**Comment by jealous** [comment]
Hi Sunny,

You have raised a good point.  So far there is no way in the API to list all hosts.

Regarding connecting host and LUN, you could do this.

``` python
storage_group = vnx.get_sg(name="xxx")

storage_group.connect_host("host_name")
```
The host name specified here is the name you could see in VNX GUI.
I will work try to create a new API to retrieve all these names.

To connect a LUN to the host, add both host and LUN in the same Storage Group
``` python
storage_group.attach_alu(lun)
```

And I believe you could create a host with following API.
``` python
sg.connect_hba(port, hba_uid, host_name, host_ip=None)
```
If host name does not exist, VNX will try to create a new host.  If it already exists, the new path will be added to that host.
Port can be retrieved by following API.
``` python
vnx.get_fc_port()
vnx.get_iscsi_port()
```
Please let me know if it works.

Cedric

**Comment by jealous** [comment]
After checking the naviseccli interface, I think there is no way to retrieve the whole host list from CLI.
Still investigating whether we could do it in another way.

**Comment by sunnyrarora** [comment]
Hi Cedric,
I am thankful to you for the reply. Yes,it seems no information to list All hosts from navisec cli. 

Regards
Sunny

**Comment by jealous** [comment]
Hi Sunny,

I was able to get a host list from the information in storage group.
Please try version 0.2.13 and use `get_host` method on `VNXSystem` to retrieve the host list.

Cedric

**Comment by sunnyrarora** [comment]
Hi Cedric,
Awesome !
With new Version 0.2.13, I am able to get the host list by `vnx.get_host()`. This is working perfectly fine. 

I just have one more small query. Now after getting the information on host details, I tried my best to look for any available option on which lun belongs to which host Or vice-versa. I mean anything which shows  Relationship between Hosts & Luns. Is there anything which we can achieve through naviseccli ? If "Yes" then Please let me know.

Thanks again.
Regards

Sunny

**Comment by jealous** [comment]
Hi Sunny,

I just update version 0.2.14.
In this version, you could access the attached LUN of the host with `VNXHost.lun_list` or `VNXHost.alu_ids`.  The previous one returns a list of `VNXLun`.  The second one returns a list of IDs.

Please let me know if it works.
Cedric

**Comment by sunnyrarora** [comment]
Hi Cedric, 
Awesome ! This works fine.
Apologies for delayed response. 

Thank you 
Regards

Sunny
