### ISSUE TITLE
Support delete tenant with its hosts

### ISSUE THREAD

**Issue by Tianqi-Tang** [emc-openstack/storops#72]
A tenant is not able to be deleted when it contains hosts. This enhancement is to add an API on the tenant object to delete the tenant along with its hosts.

**Comment by jealous** [comment]
@Tianqi-Tang , I saw the change for this issue is merged but there are still commits on going which reference this issue.  Should I keep this open?

**Comment by Tianqi-Tang** [comment]
The latest commit f4c82e7 has been merged into the develop.  It is ok to close it.
