### ISSUE TITLE
Getting all types of Capacity(Used, Free raw disk capacity,Free Storage pool capacity) for VNX

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#8]
Hi Team,
I am looking for getting information on all types storage capacity of VNX. Attached image shows "Storage capacity summary" on Unisphere Dashboard of VNX. It shows 3 types of capacity in our environment.  
"Free Storage pool capacity": 274812.95 GB( I am able to get/calculate this correctly Via Storops)
"Free raw disk capacity": 14552.92 GB
"Used Capacity": 78257.92 GB
![vnx](https://cloud.githubusercontent.com/assets/13348767/16443006/d13d7c88-3df3-11e6-9f50-0e00905f8d5e.PNG)

My Query is : How to get info on "Used" & "Free raw disk capacity" using storops.
I did some analysis as shown below.

```
>>>pools = vnx.get_pool()
>>> pools.available_capacity_gbs
[260031.885, 14781.063]
```
i.e Addition of these Two pools is 274812.948 , This is correctly shown in the Dashboard of storage for "Free Storage pool capacity".
But whenever i try to get consumed capacity,  it shows the  capacity of actual luns which are allocated from the two pools. 
```
>>> pools.consumed_capacity_gbs
[842.142, 243.976]

```

Below are some links which can be checked/referred on what exactly i am looking for.

[How does Unisphere calculates Capacity on Dashboard](https://community.emc.com/message/630742)
.
OR Is there any way we can get logical_capacity, raw_capacity, used_capacity, free_capacity as shown here [How to compile capacity and used capacity of an EMC VNX via CLI?](http://serverfault.com/questions/655505/how-to-compile-capacity-and-used-capacity-of-an-emc-vnx-via-cli)

You can also check  [Available space and Used space](https://community.emc.com/thread/163141?tstart=0)

Please let me know if you have any questions.

Thanks
Sunny

**Comment by sunnyrarora** [comment]
Hi Cedric/Tina,
Thank you so much for all the support and help.

Regards
Sunny

**Comment by Tianqi-Tang** [comment]
Hi Sunny,

FYI. The Total capacity and the free raw disk capacity hasn't count on the capacity consumed by vault drivers. However, storops can't get the vault drivers capacity from naviseccli. Thus, the capacity returned by storops may not the same as GUI.

Thanks,
Tina

**Comment by jealous** [comment]
Hi Sunny,

I have merged Tina's change.  Please use `get_capacity` on `VNXSystem` to retrieve the capacity info.
As Tina said, the limitation is that we are not able to subtract the vault capacity.  So please use them with caution.  Thanks.

Cedric

**Comment by sunnyrarora** [comment]
Hi Cedric/Tina,
Thanks a lot. I was able to update the new build of Storops and now getting information on capacity.

```
>>> vnx.get_capacity()
{
    "VNXCapacity": {
        "free_raw_disk": 15626.989,
        "free_storage_pool": 274812.697,
        "total": 368708.981,
        "used": 78269.295
    }
}
```
Request you to please add `vnx.get_capacity` in help section/main page of  [storops](https://github.com/emc-openstack/storops)

Thanks again,
Regards
Sunny

**Comment by Tianqi-Tang** [comment]
This feature has been included in the "Feature List" of the readme page of storops.  Closing this issue.
