### ISSUE TITLE
Unable to run unit tests from pypi source zip

### ISSUE THREAD

**Issue by eharney** [emc-openstack/storops#92]
We are attempting to package storops to support EMC Cinder drivers in RDO and Red Hat OpenStack.  It is important for us to run unit tests to ensure the packaged library works, since we can't test it against hardware in packaging build environments.

storops-0.4.6.zip on pypi does not contain data to run unit tests.  A number of unit tests will fail with:

`OSError: file: /home/eharney/src/storops-pypi/storops-0.4.6/test/vnx/testdata/block_output/security_-certificate_-getLevel.txt not found.`

This is available in the storops git tree but is not packaged in the source zip.

Other tests also fail with:

`FileNotFoundError: [Errno 2] No such file or directory: 'naviseccli'`

which seems to indicate that the unit tests are attempting to execute "naviseccli".  This program is not available.

Please include the required test data in the storops source zip, and mock out calls to external CLI utilities.

**Comment by jealous** [comment]
Fixed in 0.4.7.
